name: Nightly Development Build

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      parameter:
        description: 'Branch to build from'
        required: true
        default: 'origin/development'
  push:
    branches:
      - origin/development

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.parameter || 'development/development' }}
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Build Shaded JAR
        run: mvn clean package

      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-${{ github.event.inputs.parameter || 'development' }}"
          prerelease: true
          title: "Nightly Build (${{ github.event.inputs.parameter || 'development' }})"
          files: |
            runelite-client/target/*.jar